"""add users table

Revision ID: 037ebe2373b5
Revises: 6982a7b467f3
Create Date: 2026-05-17 19:03:55.453654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037ebe2373b5'
down_revision: Union[str, Sequence[str], None] = '6982a7b467f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('pseudo', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'pseudo')
    # ### end Alembic commands ###
