"""add users table

Revision ID: 6982a7b467f3
Revises: fcf0e1584af9
Create Date: 2026-05-06 08:34:06.457137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6982a7b467f3'
down_revision: Union[str, Sequence[str], None] = 'fcf0e1584af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_stats', 'roblox_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'player_stats', ['roblox_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_stats', type_='unique')
    op.alter_column('player_stats', 'roblox_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
